name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        php: ['8.0', '8.1', '8.2']
        laravel: ['9.2', '9.52', '10.0', '10.5']
        exclude:
          - php: '8.0'
            laravel: '10.0'
          - php: '8.0'
            laravel: '10.5'
    name: PHP ${{ matrix.php }} Laravel ${{ matrix.laravel }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, json, sqlite3
          tools: composer:v2
      - name: Lock Laravel Version
        run: composer require "laravel/framework:${{ matrix.laravel }}.*" --no-update -v
      - name: Composer Install
        run: composer install --prefer-dist --no-progress --no-interaction
      - name: Run Tests
        run: php vendor/bin/phpunit --testdox
